name: Api

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Install Native Dependencies
        run: |
          sudo apt-get update -yqq
          sudo apt-get -yqq install libpq-dev
      - name: Use Ruby 2.4.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.4.x"
      - uses: actions/cache@v1
        with:
          path: ./api/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('api/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install Ruby Gems
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
        working-directory: ./api
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      - name: Run tests
        run: bundle exec rspec
        working-directory: ./api
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
