name: Api

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Ruby 2.4.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.4.x"
      - name: Run tests
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          sudo apt-get -yqq install libsqlite3-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails spec
        working-directory: ./api
