name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.4
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.4.x'
    - name: Add SQLite native dependencies
      run: apt-get install libsqlite3-dev
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install
        bundle exec rake
      working-directory: ./api
